### ISSUE TITLE
Version 4.0.0 does not reflect less file changes when using gulp-watch

### ISSUE THREAD

**Issue by parapada73** [gulp-community/gulp-less#283]
I am using gulp-watch (5.0.0).
After updating to 4.0.0 today, CSS is generated but the changes are not reflected.
Version 3.5.0 did not have this problem.

Below is the code that uses gulp-watch.

```
const gulp = require('gulp');
const gulp_watch = require('gulp-watch');
const gulp_messenger = require('gulp-messenger');
const gulp_plumber = require('gulp-plumber');
const gulp_less = require('gulp-less');
const path = require('path');
const beep = require('beepbeep');
const gulp_messenger = require('gulp-messenger');

const gulp_watch_options = {
	useFsEvents: true,
};

let showSuccessMessage = function(pathString){
	pathString = path.resolve(pathString);
	gulp_messenger.success('<%= name %> : maked', {name: pathString});
};

let makeCSS = function(){
	let isError = false;
	
	const sourcePath = path.join(basePath_webroot, 'WEB-INF/_ui-src/responsive/themes/fn/less/style.less');
	const basePath_target = path.join(basePath_webroot, '_ui/responsive/theme-fn/css');
	
	return gulp.src(sourcePath)
		.pipe(gulp_plumber({errorHandler: function(err){
			beep();
			gulp_messenger.error(err);
			isError = true;
			this.emit('end');
		}}))
		.pipe(gulp_less())
		.pipe(gulp.dest('.', {cwd:basePath_target}))
		.on('end', function(){
			if(!isError){
				showSuccessMessage(path.join(basePath_target, 'style.css'));
			}
			
			isError = false;
		});
};
```

**Comment by stevelacy** [comment]
"CSS is generated but the changes are not reflected" 
What does that mean?
This only updates the less binary behind the scenes, the less binary does not have anything to do with gulp's sources or files passed through the stream.

**Comment by robinparisi** [comment]
Same here. 

My gulp wach task :

```js
gulp.task('watch', () => {
    bs.init({
        server: {
            baseDir: "./dist",
        },
        open: false
    });

    gulp.watch(['src/**/*', '!src/_assets/**/*'], gulp.series('jekyll:build'));
    gulp.watch('src/_assets/less/**/*', gulp.series('css'));
    gulp.watch('src/_assets/img/**/*', gulp.series('images'));
});
```

When editing Less files, the task is trigerred:

```
[Browsersync] 1 file changed (style.css)
[16:37:43] Finished 'css' after 115 ms
[16:37:44] Starting 'css'...
```

But if I open the dist/style.css file, nothing changes (except for the first watch execution or if I run `gulp css` manually.

I'm using Gulp 4.0.0 and everything works fine with gulp-less 3.5.0.

**Comment by stevelacy** [comment]
So the changes are not reflected to the compiled output if the task is run through a subsequent build when triggered by gulp.watch?

**Comment by robinparisi** [comment]
Exactly, except for the first run:

- launch `gulp watch`
- do some changes + save
- css task is run and changes are reflected
- do some changes + save
- css task is run but changes **are not reflected**
- do some changes + save
- css task is run but changes **are not reflected**
- restart watch
- do some changes + save
- css task is run and changes are reflected
- do some changes + save
- css task is run but changes **are not reflected**
- etc...

**Comment by stevelacy** [comment]
What happens when you set `useFileCache` to true in the options?

**Comment by robinparisi** [comment]
Like this?

```
.pipe(less({
  useFileCache: true
}))
```

It doesn't change anything.

**Comment by brunofarias** [comment]
The same problem happens here

**Comment by NikitaAvvakumov** [comment]
Almost exactly the same problem here, except it's the changes to `@import`s that aren't reflected in the generated CSS. My 'watch' task monitors changes to all `*.less` files and then triggers the 'less' task that uses the main LESS file as the source. Changes made in the main file itself always end up in the CSS but changes in any of the files it imports trigger the 'less' task but the generated CSS remains the same.

**Comment by nicolasbettag** [comment]
I'm experiencing the same issue! Just downgraded to 3.5.0, now it's running again.

**Comment by stevelacy** [comment]
The only update from 3.5.0 to 4.0.0 was upgrading less, which means one of the methods the newer less uses for determining changes is altered.

**Comment by seven-phases-max** [comment]
>one of the methods the newer less uses for determining changes is altered. 

Less (its node version) itself does not cache any files (either input or output) between different sessions so the problem is somewhere in between. (More verbose log of the build process would be handy I guess).

**Comment by nicolasbettag** [comment]
I'm still trying to figure out, where the error is. Mysterious. Maybe there's an error in Gulp 4. It's still kinda buggy.

**Comment by stevelacy** [comment]
What is the OS all of you are on?

**Comment by NikitaAvvakumov** [comment]
@stevelacy macOS 10.13.3 (High Sierra)

**Comment by robinparisi** [comment]
@stevelacy macOS 10.12.6

**Comment by Falc** [comment]
@stevelacy Fedora 26 and 27

**Comment by niftylettuce** [comment]
Same error here on.  10.12.6

**Comment by UnreaLSnake** [comment]
Same error with v4.0.0 on Windows 10 (1709), downgraded to 3.5.0

**Comment by seven-phases-max** [comment]
Contrary to my comment above ("does not cache any files between different sessions"), it appears to be a Less bug as soon as it's not really *different sessions* used to compile the triggered updates but the same object (that *does* cache imports of course).

**Comment by ajhoddinott** [comment]
I’m having the same problem with 4.0.0 on macOS 10.13.3. Seeing @seven-phases-max comment about it not being different sessions, I tried and found gulp-multi-process offers a work-around:

```
gulp.task('less', function () {
  return gulp.src('*/*.less')
    .pipe(less({}))
    .pipe(gulp.dest('css'))
})

gulp.task('watch', function () {
  gulp.watch('**/*.less', function () {
    gulpMultiProcess(['less'], function () {})
  })
})
```

**Comment by fabioth** [comment]
Thanks ajhoddinott, this seems to be a workaround for now.. downside is you cannot cache the compiling task (so it doesn't have to compile everything)

**Comment by stevelacy** [comment]
@seven-phases-max Excellent, thanks for the update.

Everyone thanks for commenting and assisting, I'll see if I can help triage the less side, and get everyone back to a stable build setup.

**Comment by rejhgadellaa** [comment]
Dammit, just when I do a major upgrade of my dependencies across multiple projects, this happens.. ok I'll roll back for now and wait for a fix..

**Comment by stevelacy** [comment]
This is why I bumped the version to a major! Anyone who is on a ^3 will not hit this issue. semver FTW

**Comment by Teenie-weenie** [comment]
It looks like I have the similar problem with @import less files.

There are a few `.less` files in less folder like `style.less` (it's main working file), `colors.less`, `fonts.less`, `mixins.less` and so on.

I use @import to add additional files in main `style.less` file.

    @import "colors.less";
    @import "fonts.less";
    @import "mixins.less";


It's my gulpfile.js below

    'use strict';
    
    var gulp = require('gulp');
    var less = require('gulp-less'); 
    var browserSync = require('browser-sync').create();
    var reload      = browserSync.reload;
    var csscomb = require('gulp-csscomb');
    var autoprefixer = require('gulp-autoprefixer');
    
    function swallowError (error) {
    
      // If you want details of the error in the console
      console.log(error.toString());
    
      this.emit('end');
    }
     
     
    /* Task to compile less */
    gulp.task('compile-less', function() {  
      gulp.src('./src/less/style.less')
        .pipe(less())
    	.on('error', swallowError)
        .pipe(autoprefixer({
            browsers: ['last 2 versions'],
            cascade: false
        }))
        .pipe(csscomb())
        .pipe(gulp.dest('./prod/css/'));
    }); 
    /* Task to watch less changes */
    gulp.task('watch-less', function() {  
      gulp.watch('./src/**/*.less' , ['compile-less']);
    });
     
    gulp.task('serve', function () {
     
        // Serve files from the root of this project
        browserSync.init({
            server: {
                baseDir: "./prod/"
            }
        }); 
        gulp.watch("./src/less/*.less").on("change", reload);
        gulp.watch("./prod/*.html").on("change", reload);
    });
     
    /* Task when running `gulp` from terminal */
    gulp.task('default', ['watch-less', 'serve']);

(I used [this code][1] as example).  

So gulp works great with `style.less` file and compiles it correctly and fast, but when I'm trying to change `colors.less` file, for example, or any other imported less file, Gulp changes css only for the first time. Then css stays the same, no changes from imported less files are not reflected in css file. But for main file `style.less` Gulp works.

"browser-sync": "^2.23.6",
    "gulp": "^3.9.1",
    "gulp-autoprefixer": "^5.0.0",
    "gulp-csscomb": "^3.0.8",
    "gulp-less": "^4.0.0"

Is there any way to make it works properly?

  [1]: https://webkul.com/blog/compiling-less-file-gulp/

**Comment by Teenie-weenie** [comment]
I installed `npm install gulp-less@3.5.0` and now gulp works just fine with imported files. But now `@import (less) "../bootstrap/bootstrap.min.css";` doesn't work, I'm getting just pile of css code in console [http://prntscr.com/iphjv2](http://prntscr.com/iphjv2) and no less files are compiled.

**Comment by seven-phases-max** [comment]
@Teenie-weenie 
>`@import (less) "../bootstrap/bootstrap.min.css";`

Do not import a minified CSS as Less (a. it makes no sense. b. harder to get to a faulty expression  in case of a error). Less is not compatible with certain edge-case minified css syntax (in particular when it comes to certain IE-hacks etc.).
In short, use `@import (less) "../bootstrap/bootstrap.css";` instead.

**Comment by giando110188** [comment]
Any update about this issue?

**Comment by stevelacy** [comment]
@giando110188 https://github.com/less/less.js/issues/3185

**Comment by tiodot** [comment]
In Node environment, manual clear less compile cached file:
```
const less = require('less');
const fileManagers = less.environment && less.environment.fileManagers || [];
fileManagers.forEach(fileManager => {
     if (fileManager.contents) {
               fileManager.contents = {};
     }
});
```

**Comment by Teenie-weenie** [comment]
@tiodot could you explain please where should I add this code? In gulpfile.js?

**Comment by tiodot** [comment]
@Teenie-weenie I create an [demo registry](https://github.com/tiodot/gulp-less-demo). the gulpfile.js:
```
var lessc = require('gulp-less');
var path = require('path');
var gulp = require('gulp');
var less = require('less');
 
gulp.task('less', function () {
  return gulp.src('./less/index.less')
    .pipe(lessc())
    .pipe(gulp.dest('./build'));
});

gulp.task('watch', function() {
    gulp.watch('./less/*.less', function (files) {
        const fileManagers = less.environment && less.environment.fileManagers || [];
        fileManagers.forEach(function (fileManager) {
            if (fileManager.contents) {
                // clear the cache file;
                fileManager.contents = {};
            }
        });
        
        gulp.start('less');
    });
});

gulp.task('default', ['less', 'watch']);
```

**Comment by parapada73** [comment]
In version 3.5.0, it worked normally without clearing cache. This seems to be a difficult solution.

**Comment by nassimdonald** [comment]
I've lost a day to this bug. 😢 Thought I was going mad!
@ajhoddinott's solution worked for me - thanks a million!

**Comment by LarsDol** [comment]
Same issue here! Downgrading to version 3.5 solved the issue.

Here's the (gulp 4) task setup i'm using:

`
function buildLess(name) {
    return gulp
        .src(config[name].less.src)
        .pipe(plumber(onError))
        .pipe(less({
            plugins: [ LessPluginGlob ]
        }))
        .pipe(postcss(processors))
        .pipe(rename({basename: config[name].less.baseName}))
        .pipe(plumber.stop())
        .pipe(gulp.dest(config.distDir + '/css/'))
        .pipe(browserSync.stream());
}

function watchLess(name) {
    gulp.watch(config[name].less.watch, gulp.parallel([ `less-${name}-lint`, `less-${name}-build` ]));
}

gulp.task('less-app-build', () => buildLess('app'));
gulp.task('less-app-watch', () => watchLess('app'));
`

Would love to see a solution, so I can upgrade gulp-less to v4 once again.

**Comment by stevelacy** [comment]
Everyone - we have determined that there is an issue, and it is dependent on changes going into less.js. I will keep this open until the issue is solved.
Thanks for your patience.

**Comment by WuglyakBolgoink** [comment]
thanks... this kill our time last 2 hours. :)

**Comment by denysvitali** [comment]
Same here. On Arch Linux w/ gulp-less 4.0.0. Downgrading to 3.5.0 fixes the issue.

**Comment by BenjaminRosell** [comment]
Same here...

**Comment by stevelacy** [comment]
Please stop posting "same here". Refer to https://github.com/stevelacy/gulp-less/issues/283#issuecomment-374013558

**Comment by daspots** [comment]
@stevelacy Any updates on this?

**Comment by seven-phases-max** [comment]
@daspots No, there can't be updates until https://github.com/less/less.js/issues/3185 is fixed. There's no point in asking of "any updates?". You're either fix it yourself or politely wait for the update to come (or are you thinking they *did* an update and just hiding it from you? ;)

**Comment by WraithKenny** [comment]
Maybe gulp-less should rollback it's less version until the bug is fixed?

**Comment by stevelacy** [comment]
It is published to a major, majors are expected to be breaking changes. Publishing a patch of 4.0.1 with the prior version of less will just postpone a release of 5.0.0 with the fixed less.

**Comment by nb-ohad** [comment]
@tiodot Your workaround works in my case but I had to introduce a little important change.
The path value I get from the gulp.watch callback parameter is an absolute path while the keys in the contents object may be relative paths (depends on the way the gulp task is set up) so I had to change the code to take this into consideration in order to clear the correct key:
```
 gulp.watch('./less/*.less', function (event) {
        const fileManagers = less.environment && less.environment.fileManagers || [];
        fileManagers.forEach(function (fileManager) {
            const relativePath = path.relative(process.cwd(), event.path);
            if (fileManager.contents && fileManager.contents[relativePath]) {
                // clear the changed file cache;
                fileManager.contents[relativePath] = null;
            }
        });
        
        gulp.start('less');
    });
```

**Comment by stevelacy** [comment]
I upgraded gulp-less@3.5.0 to latest, and 4.0.0 to `next`.
Now if you install gulp-less@latest you will get 3.5.0 and not the version awaiting an update to `less`.

**Comment by WraithKenny** [comment]
I just downgraded less to 2.7.3 which is better than downgrading gulp-less, since less ^3 has other bugs (like plugins not working).

**Comment by seteam1** [comment]
This is an issue an issue for our dev team as well running on Windows 10 machines. We downgraded to 3.5 and everything started working again.

**Comment by xvilo** [comment]
Having this issue also, have been trying to wrap my head around this all day. I'm on latest FreeBSD

**Comment by xvilo** [comment]
Having this issue also, have been trying to wrap my head around this all day. I'm on latest FreeBSD
@nb-ohad's workaround seems to work here for now.

**Comment by TigersWay** [comment]
@tiodot changes have been integrated already and should not be needed outside anymore.

I'm running pretty fine with these
```
...
  "devDependencies": {
    "browser-sync": "^2.24.4",
    "gulp": "^4.0.0",
    "gulp-autoprefixer": "^5.0.0",
    "gulp-clean-css": "^3.9.4",
    "gulp-hb": "^7.0.1",
    "gulp-less": "^4.0.0",
    "gulp-load-plugins": "^1.5.0",
    "gulp-rename": "^1.2.3",
    "less-plugin-functions": "^1.0.0",
    "less-plugin-lists": "^1.1.1"
  },
  "dependencies": {
    "normalize.css": "^8.0.0"
  },
  "optionalDependencies": {
    "less": "^3.0.4"
  }
...
```

```
...
gulp.task('build:styles', () => {

  return gulp.src('css/styles.less')
    .pipe($.less({
      plugins: [
        new $.lessPluginLists(),
        new $.lessPluginFunctions()
      ]
    }))
    .pipe($.hb().data({pkg: pkg}))
    .pipe($.autoprefixer())
    .pipe(gulp.dest('css'))
    .pipe($.cleanCss({
      format: {
        breaks: {afterComment: true, afterRuleEnds: true} // Debug only
        //breaks: {afterComment: true}
      },
      level: {
        1: {specialComments: '1'},
        2: {restructureRules: true}
      }
    }))
    .pipe($.rename({suffix: '.min'}))
    .pipe(gulp.dest('css'));
});
gulp.task('watch:styles', () => {
  return gulp.watch('**/*.less', gulp.series('build:styles'));
});
...
```

**Comment by WraithKenny** [comment]
https://github.com/less/less.js/issues/3185

Looks like the upstream has it fixed, so it'll be fixed here as soon as that's published I guess.

**Comment by stevelacy** [comment]
Yeah, I'm waiting for the dependencies to update. I can send the update to accord if needed

**Comment by klimashkin** [comment]
Seems like with less 3.5.3 issue is solved, so maybe it's ok to make version 4.0.0 the latest

**Comment by stevelacy** [comment]
committed 0678856e804b0c5e4ffd9120b7623d225213a340 and published as 4.0.1

**Comment by jimlundblad** [comment]
Hi, I I'm still having issues with the @import files updating event with `4.0.1`
├── gulp@4.0.2
├── gulp-less@4.0.1
├── browser-sync@2.26.7


```
//main.less
...  
@import (less) 'type.less';
...
```

```
// gulp tasks
let styles = () => {
  return gulp
    .src(path.join(src, "main.less"))
    .pipe(less({
      paths: [ path.join(src, "includes") ]
    }))
   ...
};

let watcher = () => {
  ...
  watch([path.join(src, '*.less'), path.join(src,'**' ,'*.less') ]).on( 'all', series( styles ) )
  ...
}
```

when a `*.less` file in the `./includes` is changed the style task starts but does not registered as changed but if I then change the `main.less` file it includes the  new less file in `./includes`

**Comment by Vimiso** [comment]
None of said downgrades or workarounds worked for me, current setup:

```
"gulp": "^4.0.2",
"gulp-clean-css": "^4.2.0",
"gulp-concat": "^2.6.1",
"gulp-less": "^4.0.1",
"gulp-plumber": "^1.2.1",
"gulp-tap": "^2.0.0",
"gulp-uglify-es": "^2.0.0"
```

```
gulp.task('watch', function(callback) {
  gulp.watch('./resources/a/styles/**/*.less', gulp.series(['compile-styles']))
  gulp.watch('./resources/a/scripts/**/*.js', gulp.series(['compile-scripts']))

  return callback()
});
```

```
gulp.task('compile-styles', function(callback) {
...etc...
```
